### ISSUE TITLE
ERROR: The install method you used for conda--probably either `pip install conda`

### ISSUE THREAD

**Issue by sephib** [A3Data/hermione#13]
Hi,
I tried to install `Hermione` example and got the following error:   
```
Creating conda virtual environment hermione_prj
ERROR: The install method you used for conda--probably either `pip install conda`
or `easy_install conda`--is not compatible with using conda as an application.
If your intention is to install conda as a standalone application, currently
supported install methods include the Anaconda installer and the miniconda
installer.  You can download the miniconda installer from
https://conda.io/miniconda.html.
```  

Do I still need to download `miniconda` if I'm already installed anaconda?   
I don't have any problems installing new conda environments. 

The conda environment is  bellow  
<details>   
 <summary>conda environment</summary>

### Name                    Version                   Build  Channel  
_libgcc_mutex             0.1                 conda_forge    conda-forge  
_openmp_mutex             4.5                       0_gnu    conda-forge  
ca-certificates           2020.6.20            hecda079_0    conda-forge  
certifi                   2020.6.20        py37hc8dfbb8_0    conda-forge  
chardet                   3.0.4                    pypi_0    pypi  
conda                     4.3.16                   pypi_0    pypi  
hermione-ml               0.1.5                    pypi_0    pypi
idna                      2.10                     pypi_0    pypi
ld_impl_linux-64          2.34                 h53a641e_5    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
pip                       20.1.1                     py_1    conda-forge
pycosat                   0.6.3                    pypi_0    pypi
python                    3.7.6           cpython_h8356626_6    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
requests                  2.24.0                   pypi_0    pypi
ruamel-yaml               0.16.10                  pypi_0    pypi
ruamel-yaml-clib          0.2.0                    pypi_0    pypi
setuptools                49.1.0           py37hc8dfbb8_0    conda-forge
sqlite                    3.32.3               hcee41ef_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
urllib3                   1.25.9                   pypi_0    pypi
wheel                     0.34.2                     py_1    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
 
</details>

**Comment by neylsoncrepalde** [comment]
Hello @sephib . Sorry for the late response. Could you provide a reproducible code so we can reproduce the error? Hermione should work fine with Anaconda, no need to install miniconda too.
Thanks.

**Comment by sephib** [comment]
Hi @neylsoncrepalde - currently I'm not able to reproduce this issue, so i'll close it for now.
