### ISSUE TITLE
UML

### ISSUE THREAD

**Issue by teoria** [A3Data/hermione#15]
o relacionamento da classe Train com as outras está invertido.
o diamante deveria estar no nado da classe train nas composições

**Comment by neylsoncrepalde** [comment]
Ei Rodrigo @teoria . Tudo bom?
Obrigado pelo toque. Vamos corrigir.
Abs

**Comment by barbarasilveiraf** [comment]
Oi Rodrigo, tudo bem?

A nossa classe Train do diagrama representa o script train.py no código, a qual contém ou pode conter as demais classes: DataSource, Preprocessing, Trainer, Visualization, etc.
Por isso o diagrama está correto,  pois elas compõe o Train.

Qualquer sugestão estamos a disposição.
Att.,
Bárbara

**Comment by teoria** [comment]
Oi Barbara, exatamente!

a classe ou script que possui a instância da outra classe é a que fica com o diamante no diagrama de classe
tanto na agregação quanto na associação.

Pessoa _possui_ Mão
Carro _tem 4_ Rodas
equivale a
Train _possui_ DataSource
Train.py _possui_ Visualization

https://www.uml-diagrams.org/composition.html
https://www.guru99.com/uml-class-diagram.html
https://www.ibm.com/support/knowledgecenter/en/SS5JSH_9.5.0/com.ibm.xtools.modeler.doc/topics/ccompasn.html
https://www.visual-paradigm.com/guide/uml-unified-modeling-language/uml-aggregation-vs-composition/
https://www.visual-paradigm.com/guide/uml-unified-modeling-language/what-is-uml/
http://www.linhadecodigo.com.br/artigo/943/uml-unified-modeling-language-generalizacao-agregacao-composicao-e-dependencia.aspx

**Comment by teoria** [comment]
https://drive.google.com/file/d/1lSXfEUXSt-BSczA02AFLmzaM140S3UXd/view?usp=sharing

posicionando assim fica mais limpo de ver( ortogonal, em colunas e sem cruzamentos)

sugestão 1:
2 diagramas
um simplificado assim e um mais completo como o atual.

sugestão 2:
A parte do preprocessing ficaria mais poderosa ainda com a ideia do pycaret (https://github.com/pycaret/pycaret/blob/master/pycaret/preprocess.py)
seria uma fabrica instanciando vários tipos de preprocessadores
aí o usuário passa como argumento os preprocessadores que ele quer usar e aí internamente aplicaria na ordem

(ele fez com um monte de if ) mas poderia ser um abstract factory 
deixaria muito melhor o código

**Comment by barbarasilveiraf** [comment]
Obrigada pelo seu feedback Rodrigo!!

**Comment by teoria** [comment]
Espero poder colaborar mais com a hermione no futuro.
Parabéns pelo projeto e por abrir com a comunidade.
