### ISSUE TITLE
Pin dependencies in example project?

### ISSUE THREAD

**Issue by rmminusrslash** [A3Data/hermione#57]
Hey, I am trying the example project setup and the dependencies don't have pinned versions:
```
category-encoders
coverage
datetime
Flask
gunicorn
hermione-ml
matplotlib
mlflow
mlxtend
numpy
pandas
plotly
pytest
seaborn
scikit-learn
scipy
statsmodels
tqdm
yellowbrick
vega_datasets
altair
pandas_profiling
streamlit_pandas_profiling
interpret-community
lime
lightgbm
great-expectations
tensorflow
umap-learn
keras
pingouin==0.4.0
mpmath
```

I have quite a few conflicts with each other when trying to install on python 3.7. Perhaps pinning them could be useful?

**Comment by barbarasilveiraf** [comment]
Hello,

first, thanks for your question!
we prefer to leave as non-fixed versions to always download as current versions of projects.
