### ISSUE TITLE
pip install acusando erro de requirement

### ISSUE THREAD

**Issue by iperoyg** [A3Data/hermione#8]
Opa, ao executar o comando 

`pip install hermione-ml `

recebi o seguinte erro:

**ERROR: Could not find a version that satisfies the requirement menuinst (from conda->hermione-ml) (from versions: none) ERROR: No matching distribution found for menuinst (from conda->hermione-ml)** 

![image](https://user-images.githubusercontent.com/6048942/83696885-f5dff880-a5d3-11ea-8256-bd58ecdc775a.png)

Executei o comando um máquina Windows 10, estou com Python 3.8.3 instalado 

Alguma ideia do que pode ser?

**Comment by iperoyg** [comment]
Pessoal, não estava com o conda instalado na máquina que fiz o teste.
Baixei a versão python 3.7 do miniconda (https://docs.conda.io/en/latest/miniconda.html)

Acredito que o problema que aconteceu foi por conta disso. Será que não seria interessante validar a instalação do conda ao instalar o pacote?

**Comment by neylsoncrepalde** [comment]
> Pessoal, não estava com o conda instalado na máquina que fiz o teste.
> Baixei a versão python 3.7 do miniconda (https://docs.conda.io/en/latest/miniconda.html)
> 
> Acredito que o problema que aconteceu foi por conta disso. Será que não seria interessante validar a instalação do conda ao instalar o pacote?

Ei Arthur. De fato `hermione` depende do conda para iniciar o ambiente virtual. Ele só está disponível em distribuições Anaconda ou Miniconda. Boa dica de validar a instalação. Já vai pro backlog. Aceitamos contribuições também!!!

**Comment by neylsoncrepalde** [comment]
Documentation already updated. Still to work on miniconda install validation.

**Comment by JulianaGuama** [comment]
Montei um ambiente virtual usando Python 3.8 (da distribuição Python tradicional).
Vou precisar fazer um novo ambiente virtual com o Python do miniconda para conseguir instalar o hermione. Tive o mesmo problema que o Arthur.

**Comment by JulianaGuama** [comment]
Reportando: consegui instalar o hermione-ml usando o prompt do anaconda. Com o miniconda não foi possível a instalação por erro de ssl do miniconda mesmo.
Foi uma luta, mas estou com o pacote e vou começar a testar o framework.
