### ISSUE TITLE
Atualizar requirements.txt

### ISSUE THREAD

**Issue by victorouttes** [A3Data/hermione#9]
Pessoal, avaliem atualizar o requirements.txt pra vir com o hermione-ml, pois instalamos o hermione e só depois que ativamos o <projeto>_env com o conda. Assim, quando tentamos usar o
```
hermione train
```
no projeto criado acontece um erro, pois a lib não existe no env.

A solução é instalar manualmente o hermione dentro do env. Se viesse já no requirements.txt do projeto ficaria mais simples.

**Comment by neylsoncrepalde** [comment]
Oi Victor. Obrigado pela dica. Já foi implementado. Mais sugestões ou correções, manda pra nós.
Abraços
